# Material bibliografico

En este apartado encontrará múltiples documentos para su lectura, referentes a los temas que iremos abarcando en la asignatura durante el semestre. La idea es que lo apoyen en el desarrollo de las prácticas y en el trabajo extra - aula. Esperamos sea de su utilidad.

#### Unidad I {-}

<center>***Cuadro 5**. Material Bibliografico para la Unidad 1* </center>

|Descripción del material|
|:---|
|[Concepto de Suelos](pdf/Unidad1/Concepto_de_suelo.PDF)|
|[Clasificación taxonómica de los suelos](pdf/Unidad1/Clasificacion_de_suelos.pdf)|
|[Clave taxonómica de los suelos](pdf/Unidad1/Clave_taxonomia_suelos_2014.pdf)|
|[Condiciones limitantes y Órdenes de los suelos](pdf/Unidad1/Condiciones_limitantes_ordenes_suelos.PDF)|
|[Clasificaion taxonomica de suelos ET](pdf/Unidad1/Clasificacion_taxonomica_suelos.pdf)|
|[Factores y Procesos formadores de suelos](pdf/Unidad1/Factores_Procesos_Suelos.pdf)|
|[GeoVenezuela - Apéndice cartográfico](https://bibliofep.fundacionempresaspolar.org/publicaciones/colecciones/apendice-cartografico/ "GeoVenezuela Fundacion Empresas Polar")|

#### Unidad II {-}

<center>***Cuadro 6**. Material Bibliografico para la Unidad 2* </center>

|Descripción del material|
|:---|
|[Directivas FAO para la evaluación de tierras en agricultura de secano](pdf/Unidad2/Directivas_evaluacion_tierras_agricultura_secano.pdf)|
|[Directivas FAO para la evaluación de tierras en agricultura de regadío](pdf/Unidad2/Directivas_evaluacion_tierras_agricultura_regadio.pdf)|

---

#### Unidad III {-}

<center>***Cuadro 7**. Material Bibliografico para la Unidad 3* </center>

|Descripción del material|
|:---|
|[Evalucion de tierras con informacion escasa](pdf/Unidad3/Material_lectura_teoria_semana_15_Evalu_tierras_informacion_escasa.pdf)|

---



