# Informacion General

### Estudiantes 2023 {-}

<center>***Cuadro 8**. Estudiantes del año 2023*</center>

<div style="font-size: 10px">
|Estudiantes|Seccion|Dia|Correo|
|:---|:---:|---|:---:|
|agrinzones, daniela|01|jueves|danielagrinzones631@gmail.com|
|martinez, gabriel|01|jueves|	gabrielfmd99@gmail.com|
|martinez, denis (RETIRADO)|01|jueves|denismartz7823@gmail.com|
|ramirez, alfredo|01|jueves|at.rd14@gmail.com|
|reina, gian|01|jueves|gianalexrs@gmail.com|
|rondón, juan|01|jueves|jjrt322@gmail.com|
|yepez, alfredo|01|jueves|ayepezfranco@gmail.com|
|sanchez, jesus|01|jueves|jsdh1998@gmail.com|


<!-- <p> La columna "Suelo" se refiere al Perfil de suelos asignado para el trabajo extra - aula </p> -->
</div>

---

### Grupos y Perfiles de suelos {-}

<center>***Cuadro 9**. Grupos y perfiles de suelos para el Trabajo Extra - aula*</center>

<div style="font-size: 12px">
|Estudiantes|Seccion|Suelos|
|:---|:---:|:---:|:---:|
|agrinzones, daniela|01|Suelo 09|
|martinez, gabriel|01|Suelo 05|
|martinez, denis (RETIRADO)|01|Suelo 00|
|ramirez, alfredo|01|Suelo 10|
|reina, gian|01|Suelo 06|
|rondón, juan|01|Suelo 03|
|yepez, alfredo|01|Suelo 08|
|sanchez, jesus|01|Suelo 07|
<p> La columna <b>"Suelos"</b> se refiere al Perfil de suelo asignado a cada alumno para el trabajo extra - aula </p>
</div>
<br>

<!-- > Recuerden que hasta que no forme su grupo y se envíe a su profesor no se le asignará el Suelo para el trabajo extra - aula. -->

---

### Tipos de Utilizacion de las Tierras {-} 

A continuación se muestran los Tipos de Utilización de las Tierras (TUT) que deberán ser evaluados en cada uno de los suelos asignados. Al final deberé conocer la aptitud de sus suelos para cada TUT.


Asignación de Tipos de Utilización de Tierras para cada suelo (estudiante).

<center>***Cuadro 10**. Tipos de Utilización de Tierras para cada (estudiante).*</center>

<div style="font-size: 12px">
|Estudiantes|Suelos|TUT 1 |TUT 2|
|:---|:---:|:---:|:---:|
|agrinzones, daniela|09|Arroz|Pasto Guinea|
|martinez, gabriel|05|Tomate|Cacao|
|martinez, denis (RETIRADO)|00|----|----|
|ramirez, alfredo|10|Teca|Brachiaria mutica|
|reina, gian|06|Pasto Bermuda|Caraota|
|rondón, juan|03|Maiz|Palma Aceitera|
|yepez, alfredo|08|Girasol|Platano|
|sanchez, jesus|07|Pasto Tanner|Cafe|
</div>